name: Deploy CI/CD to LMS Production

on:
  push: # tells github to run this on any push to the repository
    branches:
      - version-14

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 90

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODCUTION_KEY }}
        port: 22
        script: |
          cd /home/frappe/frappe-bench/apps/one_lms # we move into our app's folder
          git pull upstream version-14 # we pull any changes from git
          cd /home/frappe/frappe-bench
          bench restart ${{secrets.PASSKEY}}
          # bench setup requirements
          bench migrate # sync database
          # we remove any unused dependencies
          bench doctor
